<?php
/**
 * Functions.php contains all the core functions for your theme to work properly.
 * Please do not edit this file!!
 *
 * @package Bulletin WordPress Theme
 * @since 1.0
 * @author WPExplorer : http://www.wpexplorer.com
 * @copyright Copyright (c) 2012, WPExplorer
 * @link http://www.wpexplorer.com
 */


/*--------------------------------------*/
/* Define Constants
/*--------------------------------------*/
define( 'WPEX_FUNCTION', get_template_directory_uri().'/js' );
define( 'WPEX_JS_DIR', get_template_directory_uri().'/js' );
define( 'WPEX_CSS_DIR', get_template_directory_uri().'/css' );



/*--------------------------------------*/
/* Theme Setup
/*--------------------------------------*/
function wpex_theme_setup() {

	// Content width
	if ( ! isset( $content_width ) ) {
		$content_width = 740;
	}
	
	// Localization support
	load_theme_textdomain( 'wpex', get_template_directory() .'/lang' );

	// Register navigation menus
	register_nav_menus (
		array(
			'primary'	=> __( 'Primary', 'att' )
		)
	);
		
	// Add theme support
	add_theme_support( 'post-formats', array( 'video', 'link', 'image', 'gallery' ) );
	add_theme_support( 'automatic-feed-links' );
	add_theme_support( 'custom-background' );
	add_theme_support( 'post-thumbnails' );
	add_theme_support( 'title-tag' );

}
add_action( 'after_setup_theme', 'wpex_theme_setup' );



/*--------------------------------------*/
/* Include functions
/*--------------------------------------*/
require_once ( get_template_directory() .'/functions/load-admin.php' );
require_once ( get_template_directory() .'/functions/recommend-plugins.php' );
require_once ( get_template_directory() .'/functions/hooks.php' );
require_once( get_template_directory() .'/functions/scripts.php' );
require_once( get_template_directory() .'/functions/excerpts.php' );
require_once( get_template_directory() .'/functions/load-more.php' );
require_once( get_template_directory() .'/functions/widgets/widget-areas.php' );
require_once( get_template_directory() .'/functions/widgets/widget-featured-posts.php' );
require_once( get_template_directory() .'/functions/default-image-sizes.php' );
require_once( get_template_directory() .'/functions/comments-output.php' );
require_once ( get_template_directory() .'/functions/register-slides.php' );
require_once( get_template_directory() .'/functions/aqua-resizer.php' );

if( is_admin() ) {
	//load these functions only in the admin dashboard
	require_once( get_template_directory() .'/functions/meta/meta-slides.php' );
	require_once( get_template_directory() .'/functions/meta/meta-post.php' );
} else {
	//load these functions only in the front-end only
	require_once( get_template_directory() .'/functions/pagination.php' );
	require_once( get_template_directory() .'/functions/page-nav.php' );
	require_once( get_template_directory() .'/functions/custom-password-form.php' );
	require_once( get_template_directory() .'/functions/featured-image-caption.php' );
	if( of_get_option( 'custom_wp_gallery','1' ) == 1 ) {
		require_once( get_template_directory() .'/functions/custom-wp-gallery.php' );
	}
}

// Responsive Video Embeds
add_filter('embed_oembed_html', 'wpex_embed_oembed_html', 99, 4);
if ( ! function_exists('wpex_embed_oembed_html')) {
	function wpex_embed_oembed_html($html, $url, $attr, $post_id) {
		return '<div class="responsive-video-wrap entry-video">' . $html . '</div>';
	}
}

// Returns escaped post title
function wpex_get_esc_title() {
	return esc_attr( the_title_attribute( 'echo=0' ) );
}

// Outputs escaped post title
function wpex_esc_title() {
	echo wpex_get_esc_title();
}